extends SceneTree
## Disposable, native Godot 4.7.2 acceptance for ARCONT P2 camera shot adapter.
## Produces actual Camera3D transform and MeshInstance3D world AABBs, not
## a handmade JSON snapshot. Does not claim FISURA map was executed.
func _initialize() -> void:
    call_deferred("_run")

func _run() -> void:
    var stage := Node3D.new()
    stage.name = "External game fixture"
    root.add_child(stage)
    var cam := Camera3D.new()
    cam.keep_aspect = Camera3D.KEEP_HEIGHT
    cam.fov = 70.0
    cam.position = Vector3(0,1,5)
    stage.add_child(cam)
    cam.look_at(Vector3(0,1,0),Vector3.UP)
    _add_box(stage,"central_pillar",Vector3(0,1,3),Vector3(2,3,1),"structure")
    _add_box(stage,"enemy",Vector3(0,1,0),Vector3(0.8,1.7,0.5),"enemy")
    _add_box(stage,"offscreen",Vector3(40,1,0),Vector3(1,1,1),"dressing")
    var adapter: Script = load("res://arcont_camera_shot_exporter.gd")
    if adapter == null:
        _fail("unable to load ARCONT Godot camera exporter")
        return
    var report: Dictionary = adapter.capture(cam,stage,"res://camera-evidence.json")
    if not report.get("ok",false):
        _fail(str(report.get("error","missing export result")))
        return
    var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string("res://camera-evidence.json"))
    if typeof(parsed)!=TYPE_DICTIONARY or parsed["capture_source"]!="native-godot-self-reported":
        _fail("camera JSON not generated by real Godot exporter")
        return
    if parsed["objects"].size()!=3:
        _fail("real scene world AABBs missing")
        return
    print("ARCONT NATIVE GODOT CAMERA EXPORT PASS native_meshes=%d" % parsed["objects"].size())
    quit(0)

func _add_box(parent: Node3D,label: String,at: Vector3,dims: Vector3,role: String) -> void:
    var model := MeshInstance3D.new()
    model.name=label
    var geometry:=BoxMesh.new()
    geometry.size=dims
    model.mesh=geometry
    model.position=at
    model.set_meta("arcont_visual_role",role)
    parent.add_child(model)

func _fail(message: String) -> void:
    printerr("ARCONT CAMERA ADAPTER FAIL ",message)
    quit(1)
