"""Relocate verified native scene candidates into a game-owned asset directory."""
from __future__ import annotations
import hashlib
import json
from pathlib import Path, PurePosixPath
import re
import shutil
import tempfile


def digest(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def relative(value):
    path=PurePosixPath(value)
    if not value or path.is_absolute() or '..' in path.parts or '\\' in value:
        raise ValueError('safe relative path required')
    return Path(*path.parts)


def materialize(project, source, destination, files, replace=False):
    project=Path(project).resolve()
    source_path=relative(source); target_path=relative(destination)
    if source_path.parts[:2]!=('.arcont','runs') or target_path.parts[0]!='assets':
        raise ValueError('a native candidate under .arcont/runs and a game asset destination are required')
    src=project/source_path; target=project/target_path
    for path in [src,target]:
        if project not in path.resolve().parents or any(p.is_symlink() for p in [path,*path.parents] if project==p or project in p.parents):
            raise ValueError('symlink or escaped project path')
    if not isinstance(files,dict) or not files or len(files)>5000:
        raise ValueError('explicit non-empty artifact hashes required')
    if target.exists():
        marker=target/'arcont-bundle.json'
        if not replace or not marker.is_file() or json.loads(marker.read_text()).get('owner')!='arcont-native-bundle':
            raise ValueError('refusing to replace an unmanaged asset directory')
    source_prefix='res://'+source_path.as_posix()+'/'
    target_prefix='res://'+target_path.as_posix()+'/'
    checked=[]
    for name,sha in files.items():
        path=src/relative(name)
        if path.is_symlink() or src.resolve() not in path.resolve().parents or not path.is_file() or path.stat().st_size==0 or digest(path)!=sha:
            raise ValueError('missing, escaped or modified artifact: '+name)
        if path.suffix not in ('.tscn','.tres','.res','.exr','.png','.lmbake'):
            raise ValueError('unsupported scene artifact: '+name)
        checked.append((name,path))
    if sum(p.stat().st_size for _,p in checked)>512*1024*1024:
        raise ValueError('scene bundle exceeds 512 MiB')
    target.parent.mkdir(parents=True,exist_ok=True)
    candidate=Path(tempfile.mkdtemp(prefix='.arcont-bundle-',dir=target.parent))
    backup=None
    try:
        output={}
        for name,path in checked:
            out=candidate/relative(name);out.parent.mkdir(parents=True,exist_ok=True)
            data=path.read_bytes()
            if path.suffix in ('.tscn','.tres'):
                text=data.decode('utf-8').replace(source_prefix,target_prefix)
                # Editor-generated resource UIDs are regenerated by the destination import.
                text=re.sub(r'(\[ext_resource[^\n]*) uid="uid://[^"]+"',r'\1',text)
                if 'res://.arcont/runs/' in text:
                    raise ValueError('reference to another unpublished bundle')
                data=text.encode('utf-8')
            elif source_prefix.encode() in data or b'res://.arcont/runs/' in data:
                raise ValueError('binary references require native reserialization before relocation')
            out.write_bytes(data);output[name]=digest(out)
        receipt={'version':1,'owner':'arcont-native-bundle','source':source_path.as_posix(),
                 'destination':target_path.as_posix(),'source_hashes':files,'output_hashes':output,
                 'limits':['Opaque binary resources are copied unchanged; compressed external references are not inspected.',
                           'Native scene reopen and exported-resource validation are required before shipping.',
                           'Artifact integrity is not visual quality or handset performance approval.']}
        (candidate/'arcont-bundle.json').write_text(json.dumps(receipt,indent=2)+'\n')
        if target.exists():
            backup=Path(tempfile.mkdtemp(prefix='.arcont-backup-',dir=target.parent));backup.rmdir();target.rename(backup)
        try:candidate.rename(target)
        except BaseException:
            if backup is not None:backup.rename(target);backup=None
            raise
        return {'ok':True,'files':len(output),'destination':destination,'receipt':str(target/'arcont-bundle.json'),
                'native_reopen_required':True}
    finally:
        if candidate.exists():shutil.rmtree(candidate)
        if backup is not None and backup.exists():shutil.rmtree(backup)
